const listaPericias = [
    { nome: "Acrobacia", attr: "destreza" },
    { nome: "Adestramento", attr: "carisma" },
    { nome: "Atuação", attr: "carisma" },
    { nome: "Bloquear", attr: "constituicao" },
    { nome: "Conhecimento", attr: "sabedoria" },
    { nome: "Corrompimento", attr: "aura" },
    { nome: "Cura", attr: "sabedoria" },
    { nome: "Diplomacia", attr: "carisma" },
    { nome: "Enganação", attr: "carisma" },
    { nome: "Fortitude", attr: "constituicao" },
    { nome: "Furtividade", attr: "destreza" },
    { nome: "Guerra", attr: "inteligencia" },
    { nome: "Iniciativa", attr: "destreza" },
    { nome: "Intimidação", attr: "aura" },
    { nome: "Investigação", attr: "inteligencia" },
    { nome: "Luta", attr: "forca" },
    { nome: "Manipulação", attr: "aura" },
    { nome: "Misticismo", attr: "inteligencia" },
    { nome: "Percepção", attr: "sabedoria" },
    { nome: "Pilotagem", attr: "sabedoria" },
    { nome: "Pontaria", attr: "destreza" },
    { nome: "Reflexos", attr: "destreza" },
    { nome: "Religião", attr: "sabedoria" },
    { nome: "Sobrevivência", attr: "sabedoria" },
    { nome: "Vontade", attr: "sabedoria" },
];
